feat:登录图形验证
BenTuTu/easy-work pull request #54
Opened 2022-05-02 04:09 UTC by wangbin980608

2022-05-08 14:34 UTC, BenTuTu commented on src/renderer/pages/Login/SwipeVerifyDialog/index.tsx
> +function SwipeVerifyDialog() {
SwiperVerifyDialog

2022-05-08 14:34 UTC, wangbin980608 commented
亲，您的邮件已经安全抵达目的地，感谢亲~

2022-05-08 14:41 UTC, BenTuTu commented on src/renderer/pages/Login/SwipeVerifyDialog/index.tsx
> +        setTimeout(() => {
why setTimeout？

2022-05-08 14:42 UTC, BenTuTu commented on src/renderer/pages/Login/SwipeVerifyDialog/index.tsx
> +            refresh();
这里应该不用refresh了

2022-05-08 14:44 UTC, BenTuTu commented on src/renderer/pages/Login/SwipeVerifyDialog/index.tsx
> +                    imgUrl={decodeURI(encodeURI(imgUrl))}
这里为什么要编码之后又解码，目的是为啥

2022-05-08 14:45 UTC, BenTuTu commented on src/renderer/pages/Login/SwipeVerifyDialog/index.tsx
> +                    onRefresh={() => refresh()}
上面三个不要箭头函数，直接写成下面的
`refresh`

2022-05-08 14:46 UTC, BenTuTu commented on src/renderer/pages/Login/index.tsx
> +			toggleSwipeVerifyDialog(true);
这边顺序不对，应该是滑动验证码成功之后再调登录接口

2022-05-11 04:04 UTC, BenTuTu requested changes

2022-05-11 04:04 UTC, BenTuTu commented on src/renderer/pages/Login/SlideVerifyDialog/index.tsx
> +export interface userProps {
UserProps

2022-05-11 04:04 UTC, BenTuTu commented on src/renderer/pages/Login/index.tsx
>  	const login = async () => {
去掉 async

2022-05-15 10:27 UTC, merged